### ISSUE TITLE
Request for dataset download location

### ISSUE THREAD

**Issue by awkrail** [ttgeng233/UnAV#6]
Hi, thank you for sharing interesting work!
I tried to download the UnAV100 dataset, but Baidu pan requires me to create Baidu account.
Because Chinese phone number is needed to create Baidu account and I don't have it, I could not download the dataset.
Could you share the dataset with other cloud services, such as Google drive and one drive?

**Comment by 1980x** [comment]
Hello. I am also not able to download the dataset. Can you please help?

**Comment by ttengwang** [comment]
@1980x Hi, the google drive link is at https://drive.google.com/drive/folders/1X4eoCPPtqi0_IKd2JGOv_q383xd27Ybb

**Comment by 1980x** [comment]
Thanks a lot.
